import { CollectionCategory, Region } from '@/types/collection';

export const CATEGORIES: CollectionCategory[] = [
  { id: 'coins', name: 'Монеты' },
  { id: 'banknotes', name: 'Банкноты' },
  { id: 'stamps', name: 'Марки' },
  { id: 'badges', name: 'Значки' },
  { id: 'medals', name: 'Медали' },
  { id: 'books', name: 'Книги' },
  { id: 'cameras', name: 'Фотоаппараты' },
  { id: 'envelopes', name: 'Конверты' },
  { id: 'postcards', name: 'Почтовые карточки' },
  { id: 'lighters', name: 'Зажигалки' },
  { id: 'watches', name: 'Часы' },
  { id: 'sugarPackets', name: 'Сахар в пакетиках' },
  { id: 'teaBags', name: 'Чайные ярлычки' },
  { id: 'vintage', name: 'Винтаж' },
  { id: 'stampCancellations', name: 'Штемпели' },
  { id: 'cars', name: 'Машинки' },
  { id: 'chevrons', name: 'Шевроны' },
  { id: 'candyWrappers', name: 'Обертки конфет' },
  { id: 'wwiiItems', name: 'Предметы ВОВ' },
  { id: 'toys', name: 'Игрушки Плангонология (куклы)' },
  { id: 'minerals', name: 'Минералы и камни' },
  { id: 'vinyl', name: 'Виниловые пластинки' },
  { id: 'plasticCards', name: 'Пластиковые карточки' },
  { id: 'christmasOrnaments', name: 'Ёлочные игрушки' },
  { id: 'knives', name: 'Ножи' },
  { id: 'wargame', name: 'Варгейм' },
  { id: 'painting', name: 'Живопись' },
  { id: 'icons', name: 'Иконы' },
  { id: 'pictures', name: 'Картины' },
  { id: 'receipts', name: 'Чеки' },
  { id: 'coupons', name: 'Талоны' },
  { id: 'tickets', name: 'Билеты' },
  { id: 'tokens', name: 'Жетоны' },
  { id: 'porcelain', name: 'Фарфор' },
  { id: 'militaryBadges', name: 'Эмблемы войск' },
  { id: 'kinderToys', name: 'Киндер игрушки' },
  { id: 'mobilePhones', name: 'Сотовые телефоны' },
  { id: 'cigarettePacks', name: 'Пачки сигарет' },
  { id: 'samovars', name: 'Самовары' },
  { id: 'loans', name: 'Займ' },
  { id: 'lotteryTickets', name: 'Лотерейные билеты' },
  { id: 'busts', name: 'Бюсты' },
  { id: 'stocks', name: 'Акции' },
  { id: 'bonds', name: 'Облигации' },
  { id: 'misc', name: 'Разное' },
];

export const REGIONS: Region[] = [
  { id: 'russia', name: 'Россия' },
  { id: 'cis', name: 'СНГ' },
  { id: 'foreign', name: 'Зарубежные' },
];

export const POSTCARD_SUBCATEGORIES = [
  { id: 'originalStamp', name: 'C оригинальной маркой' },
  { id: 'marked', name: 'Маркированные' },
  { id: 'greeting', name: 'Поздравительные' },
  { id: 'double', name: 'Двойные открытки' },
  { id: 'unmarked', name: 'Немаркированные' },
  { id: 'telegraphForms', name: 'Телеграфные бланки' },
  { id: 'cartMaximum', name: 'Картмаксимум' },
  { id: 'radioNetwork', name: 'Карточки радиотрасляционной сети' },
];

export const STAMP_CANCELLATION_SUBCATEGORIES = [
  { id: 'specialPostal', name: 'Специальные почтовые' },
  { id: 'souvenirNonPostal', name: 'Сувенирные непочтовые' },
];