export type FieldDefinition = {
  key: string;
  label: string;
  dropdownKey?: string;
};

export const fieldDefinitions: Record<string, FieldDefinition[]> = {
  watches: [
    { key: 'brand', label: 'Фирма' },
    { key: 'gender', label: 'Пол', dropdownKey: 'gender' },
    { key: 'type', label: 'Тип', dropdownKey: 'type_watch' },
    { key: 'metal', label: 'Металл', dropdownKey: 'metal_watch' },
    { key: 'diameter', label: 'Диаметр' },
    { key: 'additional', label: 'Дополнительно' },
    { key: 'condition', label: 'Состояние' },
  ],
  banknotes: [
    { key: 'nominal', label: 'Номинал' },
    { key: 'country', label: 'Страна' },
    { key: 'size', label: 'Размер банкноты' },
    { key: 'circulationStart', label: 'Введение в обращение' },
    { key: 'krauseNumber', label: 'Номер по Краузе' },
    { key: 'vikNumber', label: 'Номер по ВИК' },
    { key: 'description', label: 'Описание' },
    { key: 'note', label: 'Заметка' },
    { key: 'modification', label: 'Модификация' },
    { key: 'condition', label: 'Состояние' },
    { key: 'material', label: 'Материал', dropdownKey: 'material_banknote' },
    { key: 'slab', label: 'СЛАБ' },
  ],
  coins: [
    { key: 'weight', label: 'Вес' },
    { key: 'edge', label: 'Гурт' },
    { key: 'mint', label: 'Монетный двор' },
    { key: 'mintage', label: 'Тираж' },
    { key: 'metal', label: 'Металл' },
    { key: 'diameter', label: 'Диаметр' },
    { key: 'thickness', label: 'Толщина' },
    { key: 'description', label: 'Описание' },
    { key: 'note', label: 'Заметка' },
    { key: 'krauseNumber', label: 'Номер по Краузе' },
    { key: 'condition', label: 'Состояние' },
    { key: 'slab', label: 'СЛАБ' },
  ],
  cameras: [
    { key: 'brand', label: 'Фирма' },
    { key: 'series', label: 'Серия' },
    { key: 'type', label: 'Тип', dropdownKey: 'type_camera' },
    { key: 'compact', label: 'Мыльница' },
    { key: 'filmFormat', label: 'Формат пленки' },
    { key: 'lens', label: 'Объектив' },
    { key: 'sensorFormat', label: 'Формат сенсора' },
    { key: 'additional', label: 'Дополнительно' },
    { key: 'condition', label: 'Состояние' },
  ],
  stamps: [
    { key: 'catalogNumber', label: 'Номер по каталогу' },
    { key: 'printType', label: 'Способ печати' },
    { key: 'perforation', label: 'Перфорация' },
    { key: 'format', label: 'Формат' },
    { key: 'mintage', label: 'Тираж' },
    { key: 'paperType', label: 'Бумага' },
    { key: 'description', label: 'Описание' },
    { key: 'note', label: 'Заметка' },
    { key: 'condition', label: 'Состояние' },
  ],
  badges: [
    { key: 'stamp', label: 'Клеймо' },
    { key: 'metal', label: 'Металл' },
    { key: 'enamel', label: 'Эмаль' },
    { key: 'fastener', label: 'Крепление' },
    { key: 'description', label: 'Описание' },
    { key: 'note', label: 'Заметка' },
    { key: 'condition', label: 'Состояние' },
  ],
  vinylRecords: [
    { key: 'format', label: 'Формат' },
    { key: 'color', label: 'Цвет' },
    { key: 'shape', label: 'Форма' },
    { key: 'additional', label: 'Дополнительно' },
    { key: 'condition', label: 'Состояние' },
  ],
  christmasToys: [
    { key: 'material', label: 'Материал' },
    { key: 'theme', label: 'Тематика' },
    { key: 'mintage', label: 'Тираж' },
    { key: 'additional', label: 'Дополнительно' },
    { key: 'condition', label: 'Состояние' },
  ],
  toys: [
    { key: 'material', label: 'Материал' },
    { key: 'condition', label: 'Состояние' },
    { key: 'additional', label: 'Дополнительно' },
  ],
  minerals: [
    { key: 'size', label: 'Размер' },
    { key: 'rarity', label: 'Редкость' },
    { key: 'additional', label: 'Дополнительно' },
  ],
  paintings: [
    { key: 'artist', label: 'Художник' },
    { key: 'additional', label: 'Дополнительно' },
  ],
  icons: [
    { key: 'artist', label: 'Художник' },
    { key: 'additional', label: 'Дополнительно' },
  ],
  vintage: [
    { key: 'description', label: 'Описание' },
    { key: 'condition', label: 'Состояние' },
    { key: 'additional', label: 'Дополнительно' },
  ],
  stampCancellations: [
    { key: 'description', label: 'Описание' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  cars: [
    { key: 'description', label: 'Описание' },
    { key: 'condition', label: 'Состояние' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  candyWrappers: [
    { key: 'factory', label: 'Фирма/Завод' },
    { key: 'condition', label: 'Состояние' },
    { key: 'description', label: 'Описание' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  wwiiItems: [
    { key: 'description', label: 'Описание' },
    { key: 'condition', label: 'Состояние' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  kinderToys: [
    { key: 'factory', label: 'Завод/Фирма' },
    { key: 'description', label: 'Описание' },
    { key: 'condition', label: 'Состояние' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  postcards: [
    { key: 'catalogNumber', label: 'Номер по каталогу АО "Марка"' },
    { key: 'description', label: 'Описание' },
    { key: 'condition', label: 'Состояние' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  chevrons: [
    { key: 'description', label: 'Описание' },
    { key: 'condition', label: 'Состояние' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  militaryBadges: [
    { key: 'type', label: 'Тип', dropdownKey: 'type_militaryBadge' },
    { key: 'branch', label: 'Род войск' },
    { key: 'country', label: 'Страна' },
    { key: 'material', label: 'Материал' },
    { key: 'size', label: 'Размер (мм)' },
    { key: 'fastener', label: 'Крепление' },
    { key: 'condition', label: 'Состояние' },
    { key: 'description', label: 'Описание' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  envelopes: [
    { key: 'description', label: 'Описание' },
    { key: 'condition', label: 'Состояние' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  teaBags: [
    { key: 'condition', label: 'Состояние' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  sugarPackets: [
    { key: 'description', label: 'Описание' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  medals: [
    { key: 'condition', label: 'Состояние' },
    { key: 'description', label: 'Описание' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  books: [
    { key: 'author', label: 'Автор' },
    { key: 'condition', label: 'Состояние' },
    { key: 'description', label: 'Описание' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  lighters: [
    { key: 'description', label: 'Описание' },
    { key: 'condition', label: 'Состояние' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  plasticCards: [
    { key: 'material', label: 'Материал' },
    { key: 'theme', label: 'Тема' },
    { key: 'size', label: 'Размер' },
    { key: 'additional', label: 'Дополнительно' },
    { key: 'condition', label: 'Состояние' },
    { key: 'price', label: 'Цена' },
  ],
  painting: [
    { key: 'artist', label: 'Художник' },
    { key: 'additional', label: 'Дополнительно' },
    { key: 'price', label: 'Цена' },
  ],
  pictures: [
    { key: 'artist', label: 'Художник' },
    { key: 'additional', label: 'Дополнительно' },
    { key: 'price', label: 'Цена' },
  ],
  receipts: [
    { key: 'address', label: 'Адрес' },
    { key: 'placeOfUse', label: 'Место использования' },
    { key: 'ticketType', label: 'Тип чека', dropdownKey: 'ticketType' },
    { key: 'additional', label: 'Дополнительно' },
    { key: 'condition', label: 'Состояние' },
    { key: 'price', label: 'Цена' },
  ],
  tickets: [
    { key: 'address', label: 'Адрес' },
    { key: 'placeOfUse', label: 'Место использования' },
    { key: 'ticketType', label: 'Тип билета', dropdownKey: 'ticketType' },
    { key: 'additional', label: 'Дополнительно' },
    { key: 'condition', label: 'Состояние' },
    { key: 'price', label: 'Цена' },
    { key: 'slab', label: 'СЛАБ' },
  ],
  coupons: [
    { key: 'address', label: 'Адрес' },
    { key: 'placeOfUse', label: 'Место использования' },
    { key: 'ticketType', label: 'Тип купона', dropdownKey: 'ticketType' },
    { key: 'additional', label: 'Дополнительно' },
    { key: 'condition', label: 'Состояние' },
    { key: 'price', label: 'Цена' },
  ],
  lotteryTickets: [
    { key: 'company', label: 'Фирма' },
    { key: 'theme', label: 'Тема' },
    { key: 'rarity', label: 'Редкость' },
    { key: 'condition', label: 'Состояние' },
    { key: 'quantity', label: 'Количество' },
    { key: 'description', label: 'Описание' },
    { key: 'price', label: 'Цена' },
  ],
  bonds: [
    { key: 'type', label: 'Вид', dropdownKey: 'bondType' },
    { key: 'signature', label: 'Подпись' },
    { key: 'condition', label: 'Состояние' },
    { key: 'description', label: 'Описание' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  stocks: [
    { key: 'theme', label: 'Тема' },
    { key: 'signatures', label: 'Подписи' },
    { key: 'condition', label: 'Состояние' },
    { key: 'slab', label: 'СЛАБ' },
    { key: 'description', label: 'Описание' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  busts: [
    { key: 'theme', label: 'Тема' },
    { key: 'genre', label: 'Жанр' },
    { key: 'size', label: 'Размер (см)' },
    { key: 'sculptor', label: 'ФИО Скульптора' },
    { key: 'material', label: 'Материал' },
    { key: 'condition', label: 'Состояние' },
    { key: 'quantity', label: 'Количество' },
    { key: 'description', label: 'Описание' },
    { key: 'price', label: 'Цена' },
  ],
  wargame: [
    { key: 'stamp', label: 'Клеймо' },
    { key: 'scale', label: 'Масштаб' },
    { key: 'type', label: 'Тип', dropdownKey: 'wargameType' },
    { key: 'material', label: 'Материал' },
    { key: 'additional', label: 'Дополнительно' },
    { key: 'price', label: 'Цена' },
  ],
  knives: [
    { key: 'type', label: 'Тип ножа', dropdownKey: 'knifeType' },
    { key: 'country', label: 'Страна' },
    { key: 'metal', label: 'Металл' },
    { key: 'bladeLength', label: 'Длина лезвия (мм)' },
    { key: 'bladeWidth', label: 'Ширина лезвия (мм)' },
    { key: 'stamp', label: 'Клеймо' },
    { key: 'additional', label: 'Дополнительно' },
    { key: 'price', label: 'Цена' },
  ],
  tokens: [
    { key: 'mint', label: 'Монетный двор' },
    { key: 'country', label: 'Страна' },
    { key: 'metal', label: 'Металл' },
    { key: 'weight', label: 'Вес (г)' },
    { key: 'additional', label: 'Дополнительно' },
    { key: 'price', label: 'Цена' },
  ],
  porcelain: [
    { key: 'stamp', label: 'Клеймо' },
    { key: 'description', label: 'Описание' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  mobilePhones: [
    { key: 'brand', label: 'Фирма' },
    { key: 'model', label: 'Модель' },
    { key: 'condition', label: 'Состояние' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  cigarettePacks: [
    { key: 'brand', label: 'Фирма' },
    { key: 'city', label: 'Город' },
    { key: 'packType', label: 'Тип пачки', dropdownKey: 'packType' },
    { key: 'cigaretteType', label: 'Тип сигарет' },
    { key: 'quantity', label: 'Количество' },
    { key: 'description', label: 'Описание' },
    { key: 'price', label: 'Цена' },
  ],
  samovars: [
    { key: 'manufacturer', label: 'Производитель' },
    { key: 'metal', label: 'Металл', dropdownKey: 'samovarMetal' },
    { key: 'type', label: 'Тип', dropdownKey: 'samovarType' },
    { key: 'shape', label: 'Форма', dropdownKey: 'samovarShape' },
    { key: 'condition', label: 'Состояние' },
    { key: 'description', label: 'Описание' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ],
  loans: [
    { key: 'theme', label: 'Тема' },
    { key: 'signature', label: 'Подпись' },
    { key: 'type', label: 'Вид' },
    { key: 'condition', label: 'Состояние' },
    { key: 'description', label: 'Описание' },
    { key: 'quantity', label: 'Количество' },
    { key: 'price', label: 'Цена' },
  ]

};

export const DROPDOWN_OPTIONS = {
  gender: [
    { value: 'male', label: 'Мужские' },
    { value: 'female', label: 'Женские' },
  ],
  type_watch: [
    { value: 'quartz', label: 'Кварцевые' },
    { value: 'mechanical', label: 'Механические' },
    { value: 'hybrid', label: 'Гибридные' },
  ],
  metal_watch: [
    { value: 'white-gold', label: 'Золото белое' },
    { value: 'yellow-gold', label: 'Золото жёлтое' },
    { value: 'rose-gold', label: 'Золото розовое' },
    { value: 'silver', label: 'Серебро' },
    { value: 'platinum', label: 'Платина' },
    { value: 'stainless-steel', label: 'Сталь нержавеющая' },
    { value: 'surgical-steel', label: 'Сталь хирургическая' },
    { value: 'titanium', label: 'Титан' },
    { value: 'aluminum', label: 'Алюминий' },
    { value: 'brass', label: 'Латунь' },
    { value: 'bronze', label: 'Бронза' },
    { value: 'palladium', label: 'Палладий' },
    { value: 'rhodium', label: 'Родий (покрытие)' },
  ],
  material_banknote: [
    { value: 'paper', label: 'Бумага' },
    { value: 'plastic', label: 'Пластик' },
  ],
  type_camera: [
    { value: 'film', label: 'Пленочные' },
    { value: 'dslr', label: 'Зеркальные' },
    { value: 'mirrorless', label: 'Беззеркальные' },
  ],
  type_militaryBadge: [
    { value: 'chevron', label: 'Шеврон' },
    { value: 'cockade', label: 'Кокарда' },
    { value: 'emblem', label: 'Эмблема' },
    { value: 'patch', label: 'Нашивка' },
    { value: 'badge', label: 'Значок' },
  ],
  ticketType: [
    { value: 'bus', label: 'Автобус' },
    { value: 'trolleybus', label: 'Троллейбус' },
    { value: 'cableway', label: 'Канатка' },
    { value: 'cinema', label: 'Кинотеатр' },
    { value: 'arcade', label: 'Игровые автоматы' },
    { value: 'concert', label: 'Концертные' },
    { value: 'tram', label: 'Трамвай' },
    { value: 'air', label: 'Авиационный' },
    { value: 'rail', label: 'Железнодорожный' },
  ],
  samovarMetal: [
    { value: 'copper', label: 'Медь' },
    { value: 'brass', label: 'Латунь' },
    { value: 'silver', label: 'Серебро' },
    { value: 'gold', label: 'Золото' },
    { value: 'enamel', label: 'Эмалированные' },
  ],
  samovarType: [
    { value: 'heating', label: 'Жаровые' },
    { value: 'electric', label: 'Электрические' },
    { value: 'combined', label: 'Комбинированные' },
    { value: 'wood', label: 'Дровянные' },
  ],
  samovarShape: [
    { value: 'jar', label: 'Банка' },
    { value: 'shot', label: 'Рюмка' },
    { value: 'acorn', label: 'Желудь' },
    { value: 'oval', label: 'Овал' },
    { value: 'ball', label: 'Шар' },
  ],
  bondType: [
    { value: 'government', label: 'Государственные' },
    { value: 'municipal', label: 'Муниципальные' },
    { value: 'corporate', label: 'Корпоративные' },
  ],
  packType: [
    { value: 'hard', label: 'Твердая' },
    { value: 'soft', label: 'Мягкая' },
    { value: 'kolba', label: 'Колба' },
  ],
  knifeType: [
    { value: 'historical', label: 'Исторические' },
    { value: 'cultural', label: 'Культурные' },
    { value: 'functional', label: 'Функциональные' },
    { value: 'artistic', label: 'Художественные' },
    { value: 'individual', label: 'Индивидуальные' },
    { value: 'specific', label: 'Специфические' },
    { value: 'thematic', label: 'Тематические' },
    { value: 'folding', label: 'Складные' },
    { value: 'fixed', label: 'С фиксацией лезвия' },
    { value: 'throwing', label: 'Метательные' },
    { value: 'switchblade', label: 'Выкидные' },
  ],
  wargameType: [
    { value: 'realistic', label: 'Реалистичные' },
    { value: 'thematic', label: 'Тематические' },
    { value: 'operational', label: 'Операционные' },
    { value: 'strategic', label: 'Стратегические' },
    { value: 'anime', label: 'Аниме' },
  ],
};

export const generateCopyText = (item: any): string => {
  if (!item || typeof item !== 'object') return 'Нет данных для копирования';
  if (!item.categoryId || !(item.categoryId in fieldDefinitions)) return 'Нет данных категории';

  const categoryFields = fieldDefinitions[item.categoryId] || [];

  let lines: string[] = [
    `Название: ${item.name || ''}`,
    `Год: ${item.year || ''}`,
    `Количество: ${item.quantity || ''}`,
    `Цена: ${item.price || ''} ₽`,
    '',
  ];

  categoryFields.forEach(field => {
    let value = item[field.key];
    if (field.dropdownKey && DROPDOWN_OPTIONS[field.dropdownKey]) {
      const option = DROPDOWN_OPTIONS[field.dropdownKey].find(opt => opt.value === value);
      value = option ? option.label : value;
    }
    if (value !== undefined && value !== null && value !== '') {
      lines.push(`${field.label}: ${value}`);
    }
  });

  return lines.join('\n');
}
